/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author IT
 */
public class Carwash extends javax.swing.JFrame {

    /**
     * Creates new form Carwash
     */
    public Carwash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_nuevaPersona = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        tf_apellido = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_carros = new javax.swing.JList<>();
        sp_edad = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bt_agregarCarro = new javax.swing.JButton();
        bt_registrarCliente = new javax.swing.JButton();
        bt_registrarEmpleado = new javax.swing.JButton();
        bt_agregarCarro1 = new javax.swing.JButton();
        jd_carroCliente = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_registro = new javax.swing.JMenu();
        jmi_registrarEmpleado = new javax.swing.JMenuItem();
        jmi_registrarCliente = new javax.swing.JMenuItem();

        jPanel2.setBackground(new java.awt.Color(0, 204, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Edad:");

        list_carros.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(list_carros);

        sp_edad.setModel(new javax.swing.SpinnerNumberModel(20, 0, 130, 1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Carros:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Registro");

        bt_agregarCarro.setBackground(new java.awt.Color(255, 0, 51));
        bt_agregarCarro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bt_agregarCarro.setForeground(new java.awt.Color(255, 255, 255));
        bt_agregarCarro.setText("Agregar Carro");

        bt_registrarCliente.setBackground(new java.awt.Color(0, 0, 255));
        bt_registrarCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_registrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        bt_registrarCliente.setText("Registrar Cliente");
        bt_registrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registrarClienteActionPerformed(evt);
            }
        });

        bt_registrarEmpleado.setBackground(new java.awt.Color(0, 0, 255));
        bt_registrarEmpleado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_registrarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        bt_registrarEmpleado.setText("Registrar Empleado");

        bt_agregarCarro1.setBackground(new java.awt.Color(255, 0, 51));
        bt_agregarCarro1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bt_agregarCarro1.setForeground(new java.awt.Color(255, 255, 255));
        bt_agregarCarro1.setText("Agregar Carro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tf_apellido, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sp_edad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                .addComponent(tf_nombre))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt_agregarCarro)
                                    .addComponent(bt_agregarCarro1)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel5)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bt_registrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_registrarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bt_agregarCarro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_agregarCarro1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_registrarCliente)
                    .addComponent(bt_registrarEmpleado))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_nuevaPersonaLayout = new javax.swing.GroupLayout(jd_nuevaPersona.getContentPane());
        jd_nuevaPersona.getContentPane().setLayout(jd_nuevaPersonaLayout);
        jd_nuevaPersonaLayout.setHorizontalGroup(
            jd_nuevaPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_nuevaPersonaLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );
        jd_nuevaPersonaLayout.setVerticalGroup(
            jd_nuevaPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jd_carroClienteLayout = new javax.swing.GroupLayout(jd_carroCliente.getContentPane());
        jd_carroCliente.getContentPane().setLayout(jd_carroClienteLayout);
        jd_carroClienteLayout.setHorizontalGroup(
            jd_carroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_carroClienteLayout.setVerticalGroup(
            jd_carroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );

        jm_registro.setText("Registro");

        jmi_registrarEmpleado.setText("Registrar Empleado");
        jmi_registrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_registrarEmpleadoActionPerformed(evt);
            }
        });
        jm_registro.add(jmi_registrarEmpleado);

        jmi_registrarCliente.setText("Registrar Cliente");
        jmi_registrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_registrarClienteActionPerformed(evt);
            }
        });
        jm_registro.add(jmi_registrarCliente);

        jMenuBar1.add(jm_registro);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_registrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_registrarEmpleadoActionPerformed
        bt_registrarEmpleado.setVisible(true);
        bt_agregarCarro1.setVisible(true);

        bt_registrarCliente.setVisible(false);
        bt_agregarCarro.setVisible(false);

        jd_nuevaPersona.pack();
        jd_nuevaPersona.setModal(true);
        jd_nuevaPersona.setLocationRelativeTo(this);
        jd_nuevaPersona.setVisible(true);
    }//GEN-LAST:event_jmi_registrarEmpleadoActionPerformed

    private void jmi_registrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_registrarClienteActionPerformed
        bt_registrarEmpleado.setVisible(false);
        bt_agregarCarro1.setVisible(false);

        bt_registrarCliente.setVisible(true);
        bt_agregarCarro.setVisible(true);

        jd_nuevaPersona.pack();
        jd_nuevaPersona.setModal(true);
        jd_nuevaPersona.setLocationRelativeTo(this);
        jd_nuevaPersona.setVisible(true);
    }//GEN-LAST:event_jmi_registrarClienteActionPerformed

    private void bt_registrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registrarClienteActionPerformed
        String nombre, apellido;
        int edad;
        try {
            DefaultListModel model = (DefaultListModel) list_carros.getModel();
            if (!model.isEmpty()) {
                
                nombre = tf_nombre.getText().trim();
                apellido = tf_apellido.getText().trim();
                edad = Integer.parseInt(sp_edad.getValue().toString());
                
                Cliente c = new Cliente();
                c.setNombre(nombre);
                c.setApellido(apellido);
                c.setEdad(edad);
                
                for (int i = 0; i < model.getSize(); i++) {
                    c.setCarro((Carro)model.getElementAt(i));
                }
                
                JOptionPane.showMessageDialog(jd_nuevaPersona, "CLiente registrado.", "Registro exitoso.", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(jd_nuevaPersona, "Debe agreagar al menos un carro.", "Sin carros", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_registrarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carwash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carwash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carwash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carwash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Carwash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_agregarCarro;
    private javax.swing.JButton bt_agregarCarro1;
    private javax.swing.JButton bt_registrarCliente;
    private javax.swing.JButton bt_registrarEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog jd_carroCliente;
    private javax.swing.JDialog jd_nuevaPersona;
    private javax.swing.JMenu jm_registro;
    private javax.swing.JMenuItem jmi_registrarCliente;
    private javax.swing.JMenuItem jmi_registrarEmpleado;
    private javax.swing.JList<String> list_carros;
    private javax.swing.JSpinner sp_edad;
    private javax.swing.JTextField tf_apellido;
    private javax.swing.JTextField tf_nombre;
    // End of variables declaration//GEN-END:variables
}
